### Register

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "password": "111111",
    "name": "manhtuan",
    "phone": "0363073478",
    "role": "ROLE2"
}

###

POST http://localhost:5000/api/auth/sign-in
Content-Type: application/json

{
    "password": "123445",
    "phone": "1235466"
}